version: '3'

services:
  django: &django
    image: infrascielo/upload
    container_name: upload_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start

  # nginx:
  #     image: nginx:latest
  #     container_name: upload_nginx
  #     volumes:
  #         - ./nginx/conf.d:/etc/nginx/conf.d
  #         - ./nginx/logs:/var/log/nginx/
  #     ports:
  #         - "81:80"

  minio:
      image: 'bitnami/minio:latest'
      container_name: upload_production_minio
      hostname: opac-minio
      ports:
          - '9000:9000'
          - '9001:9001'
      environment:
          - MINIO_ROOT_USER=minio
          - MINIO_ROOT_PASSWORD=minio123
      volumes:
          - './data/minio:/bitnami/minio/data'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: upload_production_postgres
    container_name: upload_production_postgres
    volumes:
      - ../scms_data/data_prod:/var/lib/postgresql/data:Z
      - ../scms_data/data_prod_backup:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6
    container_name: upload_production_redis

  celeryworker:
    <<: *django
    container_name: upload_production_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    container_name: upload_production_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    container_name: upload_production_flower
    command: /start-flowe
    ports: []